### ISSUE TITLE
De boas image is sad

### ISSUE THREAD

**Issue by hmmoreira** [ftuyama/slack-checker#1]
When I click on the `Ah, de boas` button, it shows a sad Naruto image, but I think it should show a de boas Naruto (for example: https://cdn.myanimelist.net/s/common/uploaded_files/1446099938-86c1f64da68da1e8099c63c6a4b557ac.jpeg).

![image](https://cdn.myanimelist.net/s/common/uploaded_files/1446099938-86c1f64da68da1e8099c63c6a4b557ac.jpeg)

**Comment by ftuyama** [comment]
A `DEATH` is always a tough moment, bro. You never really have a choice, it's always painful.
